.PHONY: clean All

All:
	@echo "----------Building project:[ TcpClient_Async - Debug ]----------"
	@cd "TcpClient_Async" && "$(MAKE)" -f  "TcpClient_Async.mk"
clean:
	@echo "----------Cleaning project:[ TcpClient_Async - Debug ]----------"
	@cd "TcpClient_Async" && "$(MAKE)" -f  "TcpClient_Async.mk" clean
