del AllSolutions.sdf
del BasicTypes\*.bak
del BasicTypes\*.ncb
del BasicTypes\*.sdf
del BasicTypes\Debug\*.idb
del BasicTypes\Debug\*.ilk
del BasicTypes\Debug\*.lib
del BasicTypes\Debug\*.log
del BasicTypes\Debug\*.obj
del BasicTypes\Debug\*.pch
del BasicTypes\Debug\*.pdb
del BasicTypes\Debug\*.sbr
del BasicTypes\Debug\*.tlog
del BasicTypes\Debug\*.lastbuildstate
del Collections.sdf
del Collections\*.bak
del Collections\*.ncb
del Collections\*.sdf
del Collections\Debug\*.idb
del Collections\Debug\*.ilk
del Collections\Debug\*.lib
del Collections\Debug\*.log
del Collections\Debug\*.obj
del Collections\Debug\*.pch
del Collections\Debug\*.pdb
del Collections\Debug\*.sbr
del Collections\Debug\*.tlog
del Collections\Debug\*.lastbuildstate
del FileUtils.sdf
del FileUtils\*.bak
del FileUtils\*.ncb
del FileUtils\*.sdf
del FileUtils\Debug\*.idb
del FileUtils\Debug\*.ilk
del FileUtils\Debug\*.lib
del FileUtils\Debug\*.log
del FileUtils\Debug\*.obj
del FileUtils\Debug\*.pch
del FileUtils\Debug\*.pdb
del FileUtils\Debug\*.sbr
del FileUtils\Debug\*.tlog
del FileUtils\Debug\*.lastbuildstate
del Graphics.sdf
del Graphics\*.bak
del Graphics\*.ncb
del Graphics\*.sdf
del Graphics\Debug\*.idb
del Graphics\Debug\*.ilk
del Graphics\Debug\*.lib
del Graphics\Debug\*.log
del Graphics\Debug\*.obj
del Graphics\Debug\*.pch
del Graphics\Debug\*.pdb
del Graphics\Debug\*.sbr
del Graphics\Debug\*.tlog
del Graphics\Debug\*.lastbuildstate
del Math\*.bak
del Math\*.ncb
del Math\*.sdf
del Math\Debug\*.idb
del Math\Debug\*.ilk
del Math\Debug\*.lib
del Math\Debug\*.log
del Math\Debug\*.obj
del Math\Debug\*.pch
del Math\Debug\*.pdb
del Math\Debug\*.sbr
del Math\Debug\*.tlog
del Math\Debug\*.lastbuildstate
del Persistence\*.bak
del Persistence\*.ncb
del Persistence\*.sdf
del Persistence\Debug\*.idb
del Persistence\Debug\*.ilk
del Persistence\Debug\*.lib
del Persistence\Debug\*.log
del Persistence\Debug\*.obj
del Persistence\Debug\*.pch
del Persistence\Debug\*.pdb
del Persistence\Debug\*.sbr
del Persistence\Debug\*.tlog
del Persistence\Debug\*.lastbuildstate
del Protocols\*.bak
del Protocols\*.ncb
del Protocols\*.sdf
del Protocols\Debug\*.idb
del Protocols\Debug\*.lib
del Protocols\Debug\*.log
del Protocols\Debug\*.obj
del Protocols\Debug\*.pch
del Protocols\Debug\*.pdb
del Protocols\Debug\*.sbr
del Protocols\Debug\*.tlog
del Protocols\Debug\*.lastbuildstate
del UnitTests\CachedUsers.dat
del UnitTests\ClonedUsers.dat
del UnitTests\*.bak
del UnitTests\*.bmp
del UnitTests\*.ncb
del UnitTests\*.sdf
del UnitTests\*.xml
del UnitTests\Debug\*.exe
del UnitTests\Debug\*.bsc
del UnitTests\Debug\*.idb
del UnitTests\Debug\*.ilk
del UnitTests\Debug\*.lib
del UnitTests\Debug\*.log
del UnitTests\Debug\*.obj
del UnitTests\Debug\*.pch
del UnitTests\Debug\*.pdb
del UnitTests\Debug\*.sbr
del UnitTests\Debug\*.tlog
del UnitTests\Debug\*.lastbuildstate
