.PHONY: clean All

All:
	@echo "----------Building project:[ Test2 - Debug ]----------"
	@cd "Test2" && "$(MAKE)" -f  "Test2.mk"
clean:
	@echo "----------Cleaning project:[ Test2 - Debug ]----------"
	@cd "Test2" && "$(MAKE)" -f  "Test2.mk" clean
