.PHONY: clean All

All:    
	@cd "BasicTypes" && "$(MAKE)" -f  "makefile"    
	@cd "Collections" && "$(MAKE)" -f  "makefile"
	@cd "FileUtils" && "$(MAKE)" -f  "makefile"
	@cd "Graphics" && "$(MAKE)" -f  "makefile"
	@cd "Logs" && "$(MAKE)" -f  "makefile"
	@cd "Math" && "$(MAKE)" -f  "makefile"
	@cd "Networking" && "$(MAKE)" -f  "makefile"
	@cd "Persistence" && "$(MAKE)" -f  "makefile"
	@cd "Protocols" && "$(MAKE)" -f  "makefile"
	@cd "Signaling" && "$(MAKE)" -f  "makefile"
	@cd "UnitTests" && "$(MAKE)" -f  "makefile"

clean:
	@cd "BasicTypes" && "$(MAKE)" -f  "makefile"  clean
	@cd "Collections" && "$(MAKE)" -f  "makefile"  clean
	@cd "FileUtils" && "$(MAKE)" -f  "makefile" clean
	@cd "Graphics" && "$(MAKE)" -f  "makefile"  clean
	@cd "Logs" && "$(MAKE)" -f  "makefile" clean
	@cd "Math" && "$(MAKE)" -f  "makefile" clean
	@cd "Networking" && "$(MAKE)" -f  "makefile" clean
	@cd "Persistence" && "$(MAKE)" -f  "makefile" clean
	@cd "Protocols" && "$(MAKE)" -f  "makefile" clean
	@cd "Signaling" && "$(MAKE)" -f  "makefile" clean
	@cd "UnitTests" && "$(MAKE)" -f  "makefile" clean